---
title: "R playground: nest()"
author: "Bill Chung"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
      number_sections: true
      fig_caption: TRUE
    css: "style.css"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(here)
source(here("source","get_lib.R"))
```

<style>
.table-hover > tbody > tr:hover { 
  background-color: #f4f442;
}
</style>

# Terms

- Sample size, number sample 
- Estimator, Random variable, statistic
  - rv, distribution, sample space, event
- distribution: normal distribution, t-distribution
- Standard error, residual, error, 
- Different types of variance 
  - population variance, 
  - variance of estimator, 
  - estimated variance of estimator, 
  - sample variance.
- Operator 
  - Expectation operator,E[X], sample mean, $\bar{x}$ 
  
|Operator | Estimator |
|:--------|:----------|
|E[X]     | $\bar{x}$|
|V[X]     | $\hat{V}[X]$|
|$V[\bar{X}]$ |$\hat{V}[\bar{X}]$|

- Joint distribution
- Marginal distribution
- Conditional distribution
- t-statistic, p-value  
- TYPE I, TYPE II Error, power of the test

## assume mean = 0

$$\text{H}_0 = 0$$
$$t = \frac{\bar{X}-0}{\sqrt{\hat{V}[\bar{X}]}}$$

# Weekly update

## WK2
1. Perform EDA and share the findings
2. Explore [CDC flueview](https://www.cdc.gov/fluview/surveillance/2025-week-09.html) 
  - Identify problem that you want to investigate. 
  - Find out the description of the given sample files

## WK3

- Type I error, Type II error

# LAB 1

[Time Series Model](https://otexts.com/fpp3/dynamic.html)

1. Develop ILI model at national level. 
2. Develop ILI model at state level. 


## resource 

[sample analysis 1](https://github.com/cdcepi/FluSight-forecasts?tab=readme-ov-file)
[R cdc package](https://github.com/hrbrmstr/cdcfluview)
[R api](https://cmu-delphi.github.io/delphi-epidata/api/fluview.html)


